# theme.toml template for a Hugo theme

name = "Ramiro V.1"
description = "My personal Theme"
homepage = "http://ramiroruiz.com/"
tags = []
features = []
min_version = "0.24.1"

[author]
  name = "Ramiro Ruiz"
  homepage = "http://ramiroruiz.com/"
